### ISSUE TITLE
sp-client-custom-fields issue with CustomListFieldType.users

### ISSUE THREAD

**Issue by MoulousSP** [OlivierCC/sp-client-custom-fields#2]
The CustomListFieldType.users have issues when using it in PropertyFieldCustomList. The user field is not stored in the properties, and loose it value in edit mode

![1](https://cloud.githubusercontent.com/assets/21206290/23546679/fc5a250e-0000-11e7-95c9-f214b1fc2765.JPG)
![2](https://cloud.githubusercontent.com/assets/21206290/23546678/fc5673be-0000-11e7-8264-1311fe7139df.JPG)
![3](https://cloud.githubusercontent.com/assets/21206290/23546677/fc55c1da-0000-11e7-974a-4b46fbcade6a.JPG)

**Comment by OlivierCC** [comment]
Thanks for this bug report. I will investigate it.
Regards,
Olivier

**Comment by OlivierCC** [comment]
Thanks again @MoulousSP. This bug is now fix with the published version 1.1.6. Let me know if the fix is working good for you, and we could close the bug if it's OK.
Regards,
Olivier

**Comment by MoulousSP** [comment]
Thank you @OlivierCC, I just created a new project to try the new version 1.1.7. now I can't event add an item with the CustomListFieldType.user, When I click ok to add an item, nothing is happening and  the console is showing somme errors :
![bug](https://cloud.githubusercontent.com/assets/21206290/23611205/72103096-0276-11e7-95cb-7d4327bb2396.JPG)

**Comment by OlivierCC** [comment]
@MoulousSP can you send me your PropertyFieldCustomList definition please ?

For example:

```
PropertyFieldCustomList('customList', {
                  label: strings.CustomListFieldLabel,
                  value: this.properties.customList,
                  headerText: "Manage News",
                  fields: [
                    { title: 'News Title', required: true, type: CustomListFieldType.string },
                    { title: 'Sub title', required: true, type: CustomListFieldType.string },
                    { title: 'Link', required: false, type: CustomListFieldType.string, hidden: true },
                    { title: 'Order', required: true, type: CustomListFieldType.number },
                    { title: 'Active', required: false, type: CustomListFieldType.boolean },
                    { title: 'Start Date', required: false, type: CustomListFieldType.date, hidden: true },
                    { title: 'End Date', required: false, type: CustomListFieldType.date, hidden: true },
                    { title: 'Picture', required: false, type: CustomListFieldType.picture, hidden: true },
                    { title: 'Users', required: false, type: CustomListFieldType.users, hidden: true }
                  ],
                  onPropertyChange: this.onPropertyPaneFieldChanged,
                  context: this.context,
                  properties: this.properties,
                  disabled: false,
                  key: 'customListFieldId'
                }),
```

Thanks by advance

**Comment by MoulousSP** [comment]
Hi @OlivierCC ,
Sorry for the late response, I just tried the actual last version (1.28) it is working :)

**Comment by MoulousSP** [comment]
{ title: 'Users', required: false, type: CustomListFieldType.users, hidden: false }.

**Comment by OlivierCC** [comment]
Thanks @MoulousSP. The version 1.3.2 fix this issue. Be careful when you will upgrade to this version: the CustomList component changed a bit with the new 'id' property in the fields. Read the warning in the documentation page to do not break your existing web parts: https://oliviercc.github.io/sp-client-custom-fields/propertyfieldcustomlist
