### ISSUE TITLE
Could you add a sortable multi field selector if possible

### ISSUE THREAD

**Issue by CStahlberg** [OlivierCC/sp-client-custom-fields#3]
- [x] Question

@OlivierCC I am not a developer but I am trying to create a custom info card for a project site but I don't know how to create a sortable list of fields (like the modern version of the modify view). 

The idea is that you select a list first then you get a list of all fields which is sortable and you can select the fields to display in the info card
![modifyview](https://cloud.githubusercontent.com/assets/24523191/23645489/a5da18ce-030c-11e7-97be-b7cc8f7f4840.PNG)

It would be great if you could add this.

**Comment by OlivierCC** [comment]
Thanks @CStahlberg for this feedback and for this idea, I will add it my todo list.
Regards,
Olivier

**Comment by CStahlberg** [comment]
Thank you very much for that. I`d really appreciate that.

**Comment by OlivierCC** [comment]
Hi @CStahlberg, the new version 1.1.8 includes now this new custom field. You can view it in the documentation here: https://github.com/OlivierCC/sp-client-custom-fields/wiki/PropertyFieldSortableList 
Thanks again for your feedback,
Regards,
Olivier

**Comment by CStahlberg** [comment]
@OlivierCC that is awesome thank you very much, this will be really useful.
Regards
Carsten
