### ISSUE TITLE
SharePoint List Query has broken filters

### ISSUE THREAD

**Issue by macica2** [OlivierCC/sp-client-custom-fields#5]
The errors seem to be in the src/PropertyFieldSPListQueryHost.tsx file. The query is being built with "$filters" instead of "$filter", which is causing the query to be incorrect and results in all list items being returned. There are still other issues, like "AND" should be "and", and operator keys need to be updated. For example, "Ge" should be "ge", "Le" should be "le", and so on. Once these strings are all fixed, the filters seem to be working again. Is this a bug, or should the filters work as is?

**Comment by TravisGilbert** [comment]
I have submitted a pull request to fix the OData query errors.

Thanks

**Comment by OlivierCC** [comment]
Thanks a lot @macica2 for your bug report and @TravisGilbert for the fix. The new version 1.3.4 has now this fix included.
